services:

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: to-do
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Laravel Backend
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
      - ./.env:/var/www/html/.env
      - ./db.sh:/var/www/html/db.sh
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: to-do
      DB_USERNAME: root
      DB_PASSWORD: 1234
    command: sh -c "./db.sh"

  # React Frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      NODE_ENV: production

volumes:
  db_data: